import type { Metadata } from 'next';
import './globals.css';
import Navbar from '@/components/ui/navbar';
import '@fontsource/inter';
import { AuthProvider } from '@/hooks/useAuth';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body>
				<AuthProvider>
					<Navbar />
					{children}
				</AuthProvider>
			</body>
		</html>
	);
}
