import type { Metadata } from 'next';
import './globals.css';
import Navbar from '@/components/ui/navbar';
import '@fontsource/inter';
import { AuthProvider } from '@/hooks/useAuth';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body>
				<AuthProvider>
					<Navbar />
					{children}
					<footer className='bg-gray-900 p-4 text-center text-white'>
						<p>© 2023 Bookworm App. All rights reserved.</p>
					</footer>
				</AuthProvider>
			</body>
		</html>
	);
}
